"""create workspace tables

Revision ID: 086c53dc1377
Revises: 593f442368a3
Create Date: 2026-09-16 23:18:04.347466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '086c53dc1377'
down_revision: str | Sequence[str] | None = '593f442368a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_definition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_definition'))
    )
    op.create_table('workspace_component',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('component_key', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('startup_command', sa.JSON(), nullable=True),
    sa.CheckConstraint('position >= 0', name=op.f('ck_workspace_component_position_non_negative')),
    sa.ForeignKeyConstraint(['definition_id'], ['workspace_definition.id'], name=op.f('fk_workspace_component_definition_id_workspace_definition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('definition_id', 'component_key', name=op.f('pk_workspace_component')),
    sa.UniqueConstraint('definition_id', 'position', name='uq_definition_id_position')
    )
    op.create_table('workspace_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workspace_definition.id'], name=op.f('fk_workspace_session_definition_id_workspace_definition'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_session'))
    )
    op.create_index(op.f('ix_workspace_session_expires_at'), 'workspace_session', ['expires_at'], unique=False)
    op.create_table('terminal_access_point_table',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('component_key', sa.String(length=128), nullable=False),
    sa.Column('command', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id', 'component_key'], ['workspace_component.definition_id', 'workspace_component.component_key'], name=op.f('fk_terminal_access_point_table_definition_id_workspace_component'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('definition_id', 'component_key', name=op.f('pk_terminal_access_point_table'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminal_access_point_table')
    op.drop_index(op.f('ix_workspace_session_expires_at'), table_name='workspace_session')
    op.drop_table('workspace_session')
    op.drop_table('workspace_component')
    op.drop_table('workspace_definition')
    # ### end Alembic commands ###
