"""create textbook and chapter tables

Revision ID: 593f442368a3
Revises:
Create Date: 2026-09-01 21:43:41.423856

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "593f442368a3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "textbook",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.CheckConstraint("title <> ''", name=op.f("ck_textbook_title_not_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_textbook")),
    )
    op.create_table(
        "chapter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("textbook_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("workspace_preset_key", sa.String(length=128), nullable=True),
        sa.CheckConstraint("title <> ''", name=op.f("ck_chapter_title_not_empty")),
        sa.CheckConstraint("position >= 0", name=op.f("ck_chapter_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["textbook_id"],
            ["textbook.id"],
            name=op.f("fk_chapter_textbook_id_textbook"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapter")),
        sa.UniqueConstraint("textbook_id", "position", name=op.f("uq_chapter_textbook_id_position")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chapter")
    op.drop_table("textbook")
    # ### end Alembic commands ###
