"""create preset workspace definition mapping table

Revision ID: b46288897efb
Revises: 086c53dc1377
Create Date: 2026-09-17 00:42:19.258769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46288897efb'
down_revision: Union[str, Sequence[str], None] = '086c53dc1377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset_workspace_definition_mapping',
    sa.Column('preset_key', sa.String(length=128), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workspace_definition.id'], name=op.f('fk_preset_workspace_definition_mapping_definition_id_workspace_definition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preset_key', name=op.f('pk_preset_workspace_definition_mapping')),
    sa.UniqueConstraint('preset_key', 'definition_id', name='uq_preset_key_definition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preset_workspace_definition_mapping')
    # ### end Alembic commands ###
